### ISSUE TITLE
Problem with migrations

### ISSUE THREAD

**Issue by alibedog** [johnitvn/yii2-user-plus#12]
According to the instructions to make the settings common / config / main.php and console \ config \ main.php continue to try to do the migration, but the error appears.
**yii migrate/up --migrationPath=@userplus/basic/migrations**
`Exception 'yii\base\InvalidParamException' with message 'Invalid path alias: @userplus/basic/migrations'

in D:\OpenServer\domains\open.ru\vendor\yiisoft\yii2\BaseYii.php:152

Stack trace:
#0 D:\OpenServer\domains\open.ru\vendor\yiisoft\yii2\console\controllers\BaseMigrateController.php(100): yii\BaseYii::getAlias('@userplus/basic...')
#1 D:\OpenServer\domains\open.ru\vendor\yiisoft\yii2\console\controllers\MigrateController.php(168): yii\console\controllers\BaseMigrateController->beforeAction(Object(yii\base\InlineAction))
#2 D:\OpenServer\domains\open.ru\vendor\yiisoft\yii2\base\Controller.php(152): yii\console\controllers\MigrateController->beforeAction(Object(yii\base\InlineAction))
#3 D:\OpenServer\domains\open.ru\vendor\yiisoft\yii2\console\Controller.php(128): yii\base\Controller->runAction('up', Array)
#4 D:\OpenServer\domains\open.ru\vendor\yiisoft\yii2\base\Module.php(454): yii\console\Controller->runAction('up', Array)
#5 D:\OpenServer\domains\open.ru\vendor\yiisoft\yii2\console\Application.php(180): yii\base\Module->runAction('migrate/up', Array)
#6 D:\OpenServer\domains\open.ru\vendor\yiisoft\yii2\console\Application.php(147): yii\console\Application->runAction('migrate/up', Array)
#7 D:\OpenServer\domains\open.ru\vendor\yiisoft\yii2\base\Application.php(375): yii\console\Application->handleRequest(Object(yii\console\Request))
#8 D:\OpenServer\domains\open.ru\yii(27): yii\base\Application->run()
#9 {main}`

Produces an error, I try to do otherwise specify the full path instead of an alias
**yii migrate/up --migrationPath=vendor\johnitvn\yii2-user-plus-master\src\basic\migrations**
`Yii Migration Tool (based on Yii v2.0.10)

Total 1 new migration to be applied:
        m150703_191015_init

Apply the above migration? (yes|no) [no]:yes
*** applying m150703_191015_init
PHP Fatal Error 'yii\base\ErrorException' with message 'Class 'johnitvn\userplus\base\migrations\BaseMigration' not found'

in D:\OpenServer\domains\open.ru\vendor\johnitvn\yii2-user-plus-master\src\basic\migrations\m150703_191015_init.php:6

Stack trace:
#0 [internal function]: yii\base\ErrorHandler->handleFatalError()
#1 {main}`

# What to do? how to solve a problem?

**Comment by alibedog** [comment]
> php yii migrate/up --migrationPath=@userplus/simple/migrations
Exception 'yii\base\InvalidParamException' with message 'Invalid path alias: @userplus/simple/migrations'

hey man what the fuck this message?
Ты дурак или как?
